name: "terragrunt Infrastructure Change Management Pipeline with GitHub Actions"

on:
  pull_request:
    branches:
      - main

jobs:
  terragrunt:
    name: "terragrunt Infrastructure Change Management"
    runs-on: self-hosted
    container:
      image: alpine/terragrunt:1.3.6
      env:
        NODE_ENV: development
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      volumes:
        - ${{ github.workspace }}:/terragrunt
      options: --cpus 2
    defaults:
      run:
        # We keep terragrunt files in the terragrunt directory.
        working-directory: /terragrunt

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Check dir /
        id: ls_root
        run: ls -lah /

      - name: Check dir
        id: ls
        run: ls -lah

      - name: terragrunt validate
        id: validate
        run: terragrunt run-all validate
        working-directory: /terragrunt/prod

      - name: terragrunt Apply
        id: apply
        run: terragrunt run-all apply -auto-approve
        working-directory: /terragrunt/prod
